name: Build Images

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Image registry'
        required: true
        default: 'registry.cn-shanghai.aliyuncs.com'
        type: choice
        options:
        - registry.cn-shanghai.aliyuncs.com
        - docker.io
      with_latest_tag:
        description: 'Build latest tag'
        required: true
        default: 'true'
        type: choice
        options:
        - true
        - false
      platform:
        description: 'Build images on different platform'
        required: true
        default: 'linux/amd64'
        type: choice
        options:
        - linux/amd64
        - linux/arm64
        - linux/amd64,linux/arm64
      target:
        description: 'Image to build'
        required: true
        default: 'dex'
        type: choice
        options:
        - dex

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Alicloud Docker registry
      if: inputs.registry == 'registry.cn-shanghai.aliyuncs.com'
      uses: docker/login-action@v2
      with:
        registry: registry.cn-shanghai.aliyuncs.com
        username: ${{ secrets.ALI_REGISTRY_USER }}
        password: ${{ secrets.ALI_REGISTRY_PASS }}
    - name: Login to Docker registry
      if: inputs.registry == 'docker.io'
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASS }}
    - name: Build and push Docker images
      run: |
        GOPROXY=https://proxy.golang.org,direct BUILD_LATEST=${LATEST} PLATFORM=${PLATFORM} IMAGE_PREFIX=${REGISTRY}/jibutech/ make ${TARGET%% *}.push
      env:
        TARGET: ${{ inputs.target }}
        LATEST: ${{ inputs.with_latest_tag }}
        PLATFORM: ${{ inputs.platform }}
        REGISTRY: ${{ inputs.registry }}
